---

- hosts: all
  become: true
  roles:
    - global

- hosts: uctronics_rpi4s
  become: true
  roles:
    - uctronics_rpi4

#- hosts: rpi4_k3s_nodes
#  become: true
#  roles:
#    - k3s-rpi4-global

#- hosts: k3s_servers
#  become: true
#  roles:
#    - k3s-server

#- hosts: k3s_agents
#  become: true
#  roles:
#    - k3s-agent
