---

- hosts: all
  become: true
  roles:
    - global

- hosts: rpi4_k3s_masters
  become: true
  roles:
    - k3s-rpi4-global
    - k3s-masters

- hosts: rpi4_k3s_workers
  become: true
  roles:
    - k3s-rpi4-global
    - k3s-workers
