- name: Configuring cgroups
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(?!.*? cgroup_memory=1 cgroup_enable=memory)(.*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes
  register: cgroup

- name: Rebooting node
  ansible.builtin.reboot:
  when: cgroup.changed
