- name: Enable i2c1 and set the speed
  ansible.builtin.lineinfile:
    line: dtparam=i2c_arm=on,i2c_arm_baudrate=400000
    dest: /boot/config.txt
    regexp: ^dtparam=i2c_arm=on,i2c_arm_baudrate=400000
  register: i2cl

- name: Enable shutdown button
  ansible.builtin.lineinfile:
    line: dtoverlay=gpio-shutdown,gpio_pin=4,active_low=1,gpio_pull=up
    dest: /boot/config.txt
    regexp: ^dtoverlay=gpio-shutdown,gpio_pin=4,active_low=1,gpio_pull=up
  register: shutdown_button

- name: Clone UCTRONICS' Github repository for RPI4 LCD display
  ansible.builtin.git:
    repo: https://github.com/UCTRONICS/SKU_RM0004.git
    dest: ~/SKU_RM0004/

- name: Compile RPI4 LCD display executable
  community.general.make:
    chdir: ~/SKU_RM0004/

- name: Add automatic startup of RPI4 LCD display to rc.local
  ansible.builtin.blockinfile:
    insertbefore: 'exit 0'
    block: |
      cd Â~/SKU_RM0004/
      make clean
      make
      ./display &

- name: Rebooting node
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: i2cl.changed or shutdown_button.changed
